-- Copyright (C) 2026 OpenEMR Community
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program. If not, see <https://www.gnu.org/licenses/>.
--
-- Chart Summarizer module installation SQL.
-- Run once when the module is installed via the OpenEMR module manager.
-- Subsequent schema changes should use numbered upgrade scripts (upgrade_1.sql, etc.)


-- ---------------------------------------------------------------------------
-- chart_summarizer_requests
-- Audit log and status tracker for every summary generation request.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `chart_summarizer_requests` (
    `id`               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `request_id`       CHAR(36) NOT NULL COMMENT 'UUID generated by the Python service',
    `patient_pid`      BIGINT UNSIGNED NOT NULL COMMENT 'OpenEMR patient PID (NOT name — no PHI beyond PID)',
    `provider_id`      BIGINT UNSIGNED DEFAULT NULL COMMENT 'OpenEMR user ID of requesting provider',
    `specialty`        VARCHAR(64) NOT NULL DEFAULT 'primary_care',
    `model_used`       VARCHAR(128) NOT NULL,
    `llm_provider`     VARCHAR(32) NOT NULL,
    `input_tokens`     INT UNSIGNED NOT NULL DEFAULT 0,
    `output_tokens`    INT UNSIGNED NOT NULL DEFAULT 0,
    `latency_ms`       INT UNSIGNED NOT NULL DEFAULT 0,
    `status`           ENUM('complete', 'partial', 'failed') NOT NULL DEFAULT 'complete',
    `confidence_level` ENUM('GREEN', 'YELLOW', 'RED') DEFAULT NULL,
    `created_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_request_id` (`request_id`),
    KEY `idx_patient_pid` (`patient_pid`),
    KEY `idx_provider_id` (`provider_id`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='HIPAA audit log for all chart summary requests';


-- ---------------------------------------------------------------------------
-- chart_summarizer_summaries
-- Stores approved/saved summary content (encrypted at rest).
-- Only populated after a clinician explicitly approves a summary.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `chart_summarizer_summaries` (
    `id`               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `request_id`       CHAR(36) NOT NULL COMMENT 'FK to chart_summarizer_requests.request_id',
    `patient_pid`      BIGINT UNSIGNED NOT NULL,
    `specialty`        VARCHAR(64) NOT NULL DEFAULT 'primary_care',
    -- summary_text is AES-256 encrypted before storage (PHI at rest)
    `summary_text`     MEDIUMTEXT NOT NULL COMMENT 'AES-256-GCM encrypted summary content',
    `confidence_level` ENUM('GREEN', 'YELLOW', 'RED') NOT NULL,
    `approved_by`      BIGINT UNSIGNED NOT NULL COMMENT 'OpenEMR user ID who approved the summary',
    `approved_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `is_saved_to_chart` TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_request_id` (`request_id`),
    KEY `idx_patient_pid` (`patient_pid`),
    KEY `idx_approved_by` (`approved_by`),
    KEY `idx_approved_at` (`approved_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Clinician-approved chart summaries (encrypted PHI at rest)';


-- ---------------------------------------------------------------------------
-- chart_summarizer_feedback
-- Stores clinician thumbs up/down feedback on summaries for eval improvement.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `chart_summarizer_feedback` (
    `id`          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `request_id`  CHAR(36) NOT NULL,
    `provider_id` BIGINT UNSIGNED NOT NULL,
    `rating`      TINYINT NOT NULL COMMENT '1 = thumbs up, -1 = thumbs down',
    `comment`     TEXT DEFAULT NULL COMMENT 'Optional free-text feedback (no PHI)',
    `created_at`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Clinician feedback on generated summaries for continuous improvement';
